name: lask
version: 0.1.0.0
github: "lask-task-runner/lask"
license: AGPL-3.0
author: "Toru Ikeda"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/lask-task-runner/lask#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson >= 2.0 && < 3
  - bytestring >= 0.11 && < 0.12
  - co-log-core >= 0.3.0 && < 0.4
  - directory >= 1.0 && < 2
  - free >= 5.0 && < 6
  - lens >= 5.0 && < 6
  - lsp >= 2.0 && < 3
  - megaparsec >= 9.6 && < 10
  - mtl >= 2.0 && < 3
  - optparse-applicative >= 0.18 && < 0.19
  - parser-combinators >= 1.0 && < 2
  - process >= 1.6 && < 2
  - process-extras >= 0.7 && < 0.8
  - scientific >= 0.3 && < 0.4
  - stm >= 2.0 && < 3
  - text >= 2.0 && < 3

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  lask:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lask

tests:
  lask-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lask
      - hspec >= 2.11 && < 3
      - hspec-core >= 2.11 && < 3
      - hspec-megaparsec >= 2.2 && < 3
